/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IndexView1: typeof import('./components/index/indexView1.vue')['default']
    IndexView2: typeof import('./components/index/indexView2.vue')['default']
    IndexView3: typeof import('./components/index/indexView3.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
