/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Community': RouteRecordInfo<'/Community', '/Community', Record<never, never>, Record<never, never>>,
    '/Learning': RouteRecordInfo<'/Learning', '/Learning', Record<never, never>, Record<never, never>>,
    '/Packages': RouteRecordInfo<'/Packages', '/Packages', Record<never, never>, Record<never, never>>,
    '/Play': RouteRecordInfo<'/Play', '/Play', Record<never, never>, Record<never, never>>,
    '/Tools': RouteRecordInfo<'/Tools', '/Tools', Record<never, never>, Record<never, never>>,
  }
}
